import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // Theme matched to the Kayaka Foundation logo: blue (primary) + orange (secondary/tertiary)
        outline: '#72787e',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'outline-variant': '#c2c7ce',
        'surface-container-low': '#eef3f9',
        'primary-fixed': '#d3e8ff',
        'on-surface': '#1a1c1e',
        'tertiary-fixed': '#ffdcb3',
        'surface-container-high': '#e2e9f1',
        primary: '#1577cf',
        'surface-container': '#e8eef5',
        background: '#f7fafd',
        error: '#ba1a1a',
        'surface-container-highest': '#dbe3ed',
        'on-secondary-fixed': '#301400',
        'on-error': '#ffffff',
        tertiary: '#b56717',
        'inverse-on-surface': '#eef1f6',
        'surface-dim': '#d7dde6',
        'on-primary-fixed-variant': '#08538c',
        'on-primary-fixed': '#001c39',
        'on-primary-container': '#00345a',
        'secondary-fixed': '#ffe1c9',
        'on-secondary-fixed-variant': '#8a4500',
        surface: '#f7fafd',
        'secondary-container': '#ffe1c9',
        'on-tertiary-container': '#4a2800',
        'surface-variant': '#dde3ea',
        'inverse-primary': '#9ccbf7',
        'surface-tint': '#1577cf',
        'on-tertiary-fixed': '#301a00',
        'primary-fixed-dim': '#9ccbf7',
        'tertiary-fixed-dim': '#f5b969',
        'primary-container': '#3f9fe8',
        'error-container': '#ffdad6',
        'surface-container-lowest': '#ffffff',
        'on-secondary-container': '#8a4500',
        'inverse-surface': '#2f3033',
        'on-error-container': '#93000a',
        'on-tertiary-fixed-variant': '#8a5200',
        'on-background': '#1a1c1e',
        'on-surface-variant': '#43474e',
        'secondary-fixed-dim': '#ffb77d',
        'tertiary-container': '#e89542',
        secondary: '#e87317',
        'on-tertiary': '#ffffff',
        'surface-bright': '#f7fafd',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        sm: '12px',
        xl: '80px',
        xs: '4px',
        'margin-desktop': '64px',
        md: '24px',
        gutter: '24px',
        lg: '48px',
        base: '8px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'label-sm': ['Montserrat'],
        'display-lg-mobile': ['Montserrat'],
        'display-lg': ['Montserrat'],
        'headline-lg': ['Montserrat'],
        'body-md': ['Montserrat'],
        'headline-md': ['Montserrat'],
        'body-lg': ['Montserrat'],
        'label-lg': ['Montserrat'],
        'headline-xl': ['Montserrat'],
        'body-sm': ['Montserrat'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '500' }],
        'display-lg-mobile': ['40px', { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-xl': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [forms, containerQueries],
}
